//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zek.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zek.Properties.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while approving row №{0}!.
        /// </summary>
        public static string ApproveRecordsErrorFormat {
            get {
                return ResourceManager.GetString("ApproveRecordsErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to approve this item(s)?.
        /// </summary>
        public static string ApproveRecordsQuestion {
            get {
                return ResourceManager.GetString("ApproveRecordsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while blocking row №{0}!.
        /// </summary>
        public static string BlockRecordsErrorFormat {
            get {
                return ResourceManager.GetString("BlockRecordsErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to block this item(s)?.
        /// </summary>
        public static string BlockRecordsQuestion {
            get {
                return ResourceManager.GetString("BlockRecordsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes not saved.
        /// </summary>
        public static string ChangesNotSavedErrorText {
            get {
                return ResourceManager.GetString("ChangesNotSavedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting row №{0}!.
        /// </summary>
        public static string DeleteRecordsErrorFormat {
            get {
                return ResourceManager.GetString("DeleteRecordsErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item(s)?.
        /// </summary>
        public static string DeleteRecordsQuestion {
            get {
                return ResourceManager.GetString("DeleteRecordsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while disapproving row №{0}!.
        /// </summary>
        public static string DisapproveRecordsErrorFormat {
            get {
                return ResourceManager.GetString("DisapproveRecordsErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disapprove this item(s)?.
        /// </summary>
        public static string DisapproveRecordsQuestion {
            get {
                return ResourceManager.GetString("DisapproveRecordsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes have been successfully saved! An error occurred after saved.
        /// </summary>
        public static string ErrorAfterSaveDataExceptionCaption {
            get {
                return ResourceManager.GetString("ErrorAfterSaveDataExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open after export?.
        /// </summary>
        public static string OpenAfterExportQuestion {
            get {
                return ResourceManager.GetString("OpenAfterExportQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found.
        /// </summary>
        public static string RecordNotFoundErrorText {
            get {
                return ResourceManager.GetString("RecordNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        public static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving.
        /// </summary>
        public static string SaveDataExceptionCaption {
            get {
                return ResourceManager.GetString("SaveDataExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while unblocking row №{0}!.
        /// </summary>
        public static string UnblockRecordsErrorFormat {
            get {
                return ResourceManager.GetString("UnblockRecordsErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unblock this item(s)?.
        /// </summary>
        public static string UnblockRecordsQuestion {
            get {
                return ResourceManager.GetString("UnblockRecordsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is duplicated.
        /// </summary>
        public static string ValueIsDuplicatedErrorText {
            get {
                return ResourceManager.GetString("ValueIsDuplicatedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is emtpy.
        /// </summary>
        public static string ValueIsEmtpyErrorText {
            get {
                return ResourceManager.GetString("ValueIsEmtpyErrorText", resourceCulture);
            }
        }
    }
}
