//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zek.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zek.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add record.
        /// </summary>
        public static string AddHint {
            get {
                return ResourceManager.GetString("AddHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved/Not Approved.
        /// </summary>
        public static string ApprovedNotApproved {
            get {
                return ResourceManager.GetString("ApprovedNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Approved/Not Approved records.
        /// </summary>
        public static string ApprovedNotApprovedHint {
            get {
                return ResourceManager.GetString("ApprovedNotApprovedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Record(s).
        /// </summary>
        public static string ApproveHint {
            get {
                return ResourceManager.GetString("ApproveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Refresh.
        /// </summary>
        public static string AutoRefresh {
            get {
                return ResourceManager.GetString("AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto refresh grid after child form closed.
        /// </summary>
        public static string AutoRefreshHint {
            get {
                return ResourceManager.GetString("AutoRefreshHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Fit.
        /// </summary>
        public static string BestFit {
            get {
                return ResourceManager.GetString("BestFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best fit columns.
        /// </summary>
        public static string BestFitHint {
            get {
                return ResourceManager.GetString("BestFitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Record(s).
        /// </summary>
        public static string ChooseHint {
            get {
                return ResourceManager.GetString("ChooseHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete record(s).
        /// </summary>
        public static string DeleteHint {
            get {
                return ResourceManager.GetString("DeleteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disapprove.
        /// </summary>
        public static string Disapprove {
            get {
                return ResourceManager.GetString("Disapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit record.
        /// </summary>
        public static string EditHint {
            get {
                return ResourceManager.GetString("EditHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing....
        /// </summary>
        public static string ExecutingEtc {
            get {
                return ResourceManager.GetString("ExecutingEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Grid.
        /// </summary>
        public static string ExportHint {
            get {
                return ResourceManager.GetString("ExportHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable Filter.
        /// </summary>
        public static string FilterEnableDisable {
            get {
                return ResourceManager.GetString("FilterEnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable Filter.
        /// </summary>
        public static string FilterEnableDisableHint {
            get {
                return ResourceManager.GetString("FilterEnableDisableHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter panel.
        /// </summary>
        public static string FilterPanel {
            get {
                return ResourceManager.GetString("FilterPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Filter Panel.
        /// </summary>
        public static string FilterPanelHint {
            get {
                return ResourceManager.GetString("FilterPanelHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid day.
        /// </summary>
        public static string InvalidDayErrorText {
            get {
                return ResourceManager.GetString("InvalidDayErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid month.
        /// </summary>
        public static string InvalidMonthErrorText {
            get {
                return ResourceManager.GetString("InvalidMonthErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid quarter.
        /// </summary>
        public static string InvalidQuarterErrorText {
            get {
                return ResourceManager.GetString("InvalidQuarterErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number is 6.
        /// </summary>
        public static string NumToStrMaximumDecimalsErrorText {
            get {
                return ResourceManager.GetString("NumToStrMaximumDecimalsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ESC to exit....
        /// </summary>
        public static string PressESCToExitEtc {
            get {
                return ResourceManager.GetString("PressESCToExitEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Record(s).
        /// </summary>
        public static string PrintHint {
            get {
                return ResourceManager.GetString("PrintHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh grid.
        /// </summary>
        public static string RefreshHint {
            get {
                return ResourceManager.GetString("RefreshHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;&amp; Close.
        /// </summary>
        public static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval (d:hh:mm:ss):.
        /// </summary>
        public static string SchedulerServiceIntervalLable {
            get {
                return ResourceManager.GetString("SchedulerServiceIntervalLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected rows count.
        /// </summary>
        public static string SelectedRowsCount {
            get {
                return ResourceManager.GetString("SelectedRowsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum selected rows.
        /// </summary>
        public static string SumHint {
            get {
                return ResourceManager.GetString("SumHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Columns.
        /// </summary>
        public static string SystemColumns {
            get {
                return ResourceManager.GetString("SystemColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide System columns.
        /// </summary>
        public static string SystemColumnsHint {
            get {
                return ResourceManager.GetString("SystemColumnsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top {0}.
        /// </summary>
        public static string TopRecordsCaptionFormat {
            get {
                return ResourceManager.GetString("TopRecordsCaptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top {0} records.
        /// </summary>
        public static string TopRecordsHintFormat {
            get {
                return ResourceManager.GetString("TopRecordsHintFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        public static string Unblock {
            get {
                return ResourceManager.GetString("Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
