//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zek.WSCartuB24 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cartubank.ge", ConfigurationName="WSCartuB24.WSB24Soap")]
    public interface WSB24Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cartubank.ge/ValidateKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidateKey(string ClientKey, string UniqueID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cartubank.ge/GetCompl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Zek.WSCartuB24.BR GetCompl(string ClientKey, string Terminal, string UniqueID, int Amount, string CheckDG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cartubank.ge/GetReversal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Zek.WSCartuB24.BR GetReversal(string ClientKey, string Terminal, string UniqueID, string CheckDG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cartubank.ge/ViewTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Zek.WSCartuB24.BR ViewTransaction(string ClientKey, string UniqueID, string CheckDG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cartubank.ge/ViewTransactionAmt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Zek.WSCartuB24.BR ViewTransactionAmt(string ClientKey, string UniqueID, string CheckDG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cartubank.ge/ViewRefund", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Zek.WSCartuB24.BR ViewRefund(string ClientKey, string UniqueID, string CheckDG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cartubank.ge/SendPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Zek.WSCartuB24.info SendPayment(string RetailerID, string PurchDescID, string UniqueID, int Amount, string TransDate, int SPID, string CardType, string Uri, string Status, string Reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cartubank.ge/GetRefund", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Zek.WSCartuB24.BR GetRefund(string ClientKey, string Terminal, int Amount, string UniqueID, string CheckDG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cartubank.ge/GetRepl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Zek.WSCartuB24.BR GetRepl(string ClientKey, string Terminal, int Amount, string UniqueID, string CheckDG);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cartubank.ge")]
    public partial class BR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMsgField;
        
        private string respCodeField;
        
        private string authCodeField;
        
        private string tranAmountField;
        
        private string cardField;
        
        private string expField;
        
        private string cvc2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("ErrorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RespCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
                this.RaisePropertyChanged("RespCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
                this.RaisePropertyChanged("AuthCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TranAmount {
            get {
                return this.tranAmountField;
            }
            set {
                this.tranAmountField = value;
                this.RaisePropertyChanged("TranAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Card {
            get {
                return this.cardField;
            }
            set {
                this.cardField = value;
                this.RaisePropertyChanged("Card");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Exp {
            get {
                return this.expField;
            }
            set {
                this.expField = value;
                this.RaisePropertyChanged("Exp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Cvc2 {
            get {
                return this.cvc2Field;
            }
            set {
                this.cvc2Field = value;
                this.RaisePropertyChanged("Cvc2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cartubank.ge")]
    public partial class info : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uniqueIDField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
                this.RaisePropertyChanged("UniqueID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSB24SoapChannel : Zek.WSCartuB24.WSB24Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSB24SoapClient : System.ServiceModel.ClientBase<Zek.WSCartuB24.WSB24Soap>, Zek.WSCartuB24.WSB24Soap {
        
        public WSB24SoapClient() {
        }
        
        public WSB24SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSB24SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSB24SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSB24SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateKey(string ClientKey, string UniqueID) {
            return base.Channel.ValidateKey(ClientKey, UniqueID);
        }
        
        public Zek.WSCartuB24.BR GetCompl(string ClientKey, string Terminal, string UniqueID, int Amount, string CheckDG) {
            return base.Channel.GetCompl(ClientKey, Terminal, UniqueID, Amount, CheckDG);
        }
        
        public Zek.WSCartuB24.BR GetReversal(string ClientKey, string Terminal, string UniqueID, string CheckDG) {
            return base.Channel.GetReversal(ClientKey, Terminal, UniqueID, CheckDG);
        }
        
        public Zek.WSCartuB24.BR ViewTransaction(string ClientKey, string UniqueID, string CheckDG) {
            return base.Channel.ViewTransaction(ClientKey, UniqueID, CheckDG);
        }
        
        public Zek.WSCartuB24.BR ViewTransactionAmt(string ClientKey, string UniqueID, string CheckDG) {
            return base.Channel.ViewTransactionAmt(ClientKey, UniqueID, CheckDG);
        }
        
        public Zek.WSCartuB24.BR ViewRefund(string ClientKey, string UniqueID, string CheckDG) {
            return base.Channel.ViewRefund(ClientKey, UniqueID, CheckDG);
        }
        
        public Zek.WSCartuB24.info SendPayment(string RetailerID, string PurchDescID, string UniqueID, int Amount, string TransDate, int SPID, string CardType, string Uri, string Status, string Reason) {
            return base.Channel.SendPayment(RetailerID, PurchDescID, UniqueID, Amount, TransDate, SPID, CardType, Uri, Status, Reason);
        }
        
        public Zek.WSCartuB24.BR GetRefund(string ClientKey, string Terminal, int Amount, string UniqueID, string CheckDG) {
            return base.Channel.GetRefund(ClientKey, Terminal, Amount, UniqueID, CheckDG);
        }
        
        public Zek.WSCartuB24.BR GetRepl(string ClientKey, string Terminal, int Amount, string UniqueID, string CheckDG) {
            return base.Channel.GetRepl(ClientKey, Terminal, Amount, UniqueID, CheckDG);
        }
    }
}
