//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zek.WSPayge {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderInfo", Namespace="http://schemas.datacontract.org/2004/07/PaygeRefundWcfService")]
    [System.SerializableAttribute()]
    public partial class OrderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderInfoStatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperationStatus {
            get {
                return this.OperationStatusField;
            }
            set {
                if ((this.OperationStatusField.Equals(value) != true)) {
                    this.OperationStatusField = value;
                    this.RaisePropertyChanged("OperationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderInfoStatusCode {
            get {
                return this.OrderInfoStatusCodeField;
            }
            set {
                if ((this.OrderInfoStatusCodeField.Equals(value) != true)) {
                    this.OrderInfoStatusCodeField = value;
                    this.RaisePropertyChanged("OrderInfoStatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefundStatus", Namespace="http://schemas.datacontract.org/2004/07/PaygeRefundWcfService")]
    [System.SerializableAttribute()]
    public partial class RefundStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RefundStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RefundStatusCode {
            get {
                return this.RefundStatusCodeField;
            }
            set {
                if ((this.RefundStatusCodeField.Equals(value) != true)) {
                    this.RefundStatusCodeField = value;
                    this.RaisePropertyChanged("RefundStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranCode {
            get {
                return this.TranCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TranCodeField, value) != true)) {
                    this.TranCodeField = value;
                    this.RaisePropertyChanged("TranCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefundInfo", Namespace="http://schemas.datacontract.org/2004/07/PaygeRefundWcfService")]
    [System.SerializableAttribute()]
    public partial class RefundInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RefundInfoStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Zek.WSPayge.RefundOperation[] RefundOperationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SumRefundedAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransactionAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RefundInfoStatusCode {
            get {
                return this.RefundInfoStatusCodeField;
            }
            set {
                if ((this.RefundInfoStatusCodeField.Equals(value) != true)) {
                    this.RefundInfoStatusCodeField = value;
                    this.RaisePropertyChanged("RefundInfoStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Zek.WSPayge.RefundOperation[] RefundOperations {
            get {
                return this.RefundOperationsField;
            }
            set {
                if ((object.ReferenceEquals(this.RefundOperationsField, value) != true)) {
                    this.RefundOperationsField = value;
                    this.RaisePropertyChanged("RefundOperations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SumRefundedAmount {
            get {
                return this.SumRefundedAmountField;
            }
            set {
                if ((this.SumRefundedAmountField.Equals(value) != true)) {
                    this.SumRefundedAmountField = value;
                    this.RaisePropertyChanged("SumRefundedAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactionAmount {
            get {
                return this.TransactionAmountField;
            }
            set {
                if ((this.TransactionAmountField.Equals(value) != true)) {
                    this.TransactionAmountField = value;
                    this.RaisePropertyChanged("TransactionAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefundOperation", Namespace="http://schemas.datacontract.org/2004/07/PaygeRefundWcfService")]
    [System.SerializableAttribute()]
    public partial class RefundOperation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefundCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TranCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefundCode {
            get {
                return this.RefundCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RefundCodeField, value) != true)) {
                    this.RefundCodeField = value;
                    this.RaisePropertyChanged("RefundCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TranCode {
            get {
                return this.TranCodeField;
            }
            set {
                if ((this.TranCodeField.Equals(value) != true)) {
                    this.TranCodeField = value;
                    this.RaisePropertyChanged("TranCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetails", Namespace="http://schemas.datacontract.org/2004/07/PaygeRefundWcfService")]
    [System.SerializableAttribute()]
    public partial class OrderDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardPanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantCodeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantTranCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OpsIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayMethodCodeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TestModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardPan {
            get {
                return this.CardPanField;
            }
            set {
                if ((object.ReferenceEquals(this.CardPanField, value) != true)) {
                    this.CardPanField = value;
                    this.RaisePropertyChanged("CardPan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientIp {
            get {
                return this.ClientIpField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIpField, value) != true)) {
                    this.ClientIpField = value;
                    this.RaisePropertyChanged("ClientIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantCodeName {
            get {
                return this.MerchantCodeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantCodeNameField, value) != true)) {
                    this.MerchantCodeNameField = value;
                    this.RaisePropertyChanged("MerchantCodeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantTranCode {
            get {
                return this.MerchantTranCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantTranCodeField, value) != true)) {
                    this.MerchantTranCodeField = value;
                    this.RaisePropertyChanged("MerchantTranCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpsId {
            get {
                return this.OpsIdField;
            }
            set {
                if ((this.OpsIdField.Equals(value) != true)) {
                    this.OpsIdField = value;
                    this.RaisePropertyChanged("OpsId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayMethodCodeName {
            get {
                return this.PayMethodCodeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PayMethodCodeNameField, value) != true)) {
                    this.PayMethodCodeNameField = value;
                    this.RaisePropertyChanged("PayMethodCodeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentStatus {
            get {
                return this.PaymentStatusField;
            }
            set {
                if ((this.PaymentStatusField.Equals(value) != true)) {
                    this.PaymentStatusField = value;
                    this.RaisePropertyChanged("PaymentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegDate {
            get {
                return this.RegDateField;
            }
            set {
                if ((this.RegDateField.Equals(value) != true)) {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TestMode {
            get {
                return this.TestModeField;
            }
            set {
                if ((this.TestModeField.Equals(value) != true)) {
                    this.TestModeField = value;
                    this.RaisePropertyChanged("TestMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranCode {
            get {
                return this.TranCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TranCodeField, value) != true)) {
                    this.TranCodeField = value;
                    this.RaisePropertyChanged("TranCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompletionStatus", Namespace="http://schemas.datacontract.org/2004/07/PaygeRefundWcfService")]
    [System.SerializableAttribute()]
    public partial class CompletionStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompletionStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompletionStatusCode {
            get {
                return this.CompletionStatusCodeField;
            }
            set {
                if ((this.CompletionStatusCodeField.Equals(value) != true)) {
                    this.CompletionStatusCodeField = value;
                    this.RaisePropertyChanged("CompletionStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranCode {
            get {
                return this.TranCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TranCodeField, value) != true)) {
                    this.TranCodeField = value;
                    this.RaisePropertyChanged("TranCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompletionInfo", Namespace="http://schemas.datacontract.org/2004/07/PaygeRefundWcfService")]
    [System.SerializableAttribute()]
    public partial class CompletionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CommplitionInfoStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplitionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommplitionInfoStatusCode {
            get {
                return this.CommplitionInfoStatusCodeField;
            }
            set {
                if ((this.CommplitionInfoStatusCodeField.Equals(value) != true)) {
                    this.CommplitionInfoStatusCodeField = value;
                    this.RaisePropertyChanged("CommplitionInfoStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComplitionCode {
            get {
                return this.ComplitionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplitionCodeField, value) != true)) {
                    this.ComplitionCodeField = value;
                    this.RaisePropertyChanged("ComplitionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperationStatus {
            get {
                return this.OperationStatusField;
            }
            set {
                if ((this.OperationStatusField.Equals(value) != true)) {
                    this.OperationStatusField = value;
                    this.RaisePropertyChanged("OperationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranCode {
            get {
                return this.TranCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TranCodeField, value) != true)) {
                    this.TranCodeField = value;
                    this.RaisePropertyChanged("TranCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditInfo", Namespace="http://schemas.datacontract.org/2004/07/PaygeRefundWcfService")]
    [System.SerializableAttribute()]
    public partial class CreditInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditInfoStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreditInfoStatusCode {
            get {
                return this.CreditInfoStatusCodeField;
            }
            set {
                if ((this.CreditInfoStatusCodeField.Equals(value) != true)) {
                    this.CreditInfoStatusCodeField = value;
                    this.RaisePropertyChanged("CreditInfoStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckRecurringPaymentResponse", Namespace="http://schemas.datacontract.org/2004/07/PaygeRefundWcfService")]
    [System.SerializableAttribute()]
    public partial class CheckRecurringPaymentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMsg {
            get {
                return this.ResponseMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMsgField, value) != true)) {
                    this.ResponseMsgField = value;
                    this.RaisePropertyChanged("ResponseMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringPosPaymentResponse", Namespace="http://schemas.datacontract.org/2004/07/PaygeRefundWcfService")]
    [System.SerializableAttribute()]
    public partial class RecurringPosPaymentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NextTransactionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextTransactionCode {
            get {
                return this.NextTransactionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NextTransactionCodeField, value) != true)) {
                    this.NextTransactionCodeField = value;
                    this.RaisePropertyChanged("NextTransactionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringPaymentStatus", Namespace="http://schemas.datacontract.org/2004/07/PaygeRefundWcfService")]
    [System.SerializableAttribute()]
    public partial class RecurringPaymentStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecurringPaymentStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecurringPaymentStatusCode {
            get {
                return this.RecurringPaymentStatusCodeField;
            }
            set {
                if ((this.RecurringPaymentStatusCodeField.Equals(value) != true)) {
                    this.RecurringPaymentStatusCodeField = value;
                    this.RaisePropertyChanged("RecurringPaymentStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranCode {
            get {
                return this.TranCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TranCodeField, value) != true)) {
                    this.TranCodeField = value;
                    this.RaisePropertyChanged("TranCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringPaymentInfo", Namespace="http://schemas.datacontract.org/2004/07/PaygeRefundWcfService")]
    [System.SerializableAttribute()]
    public partial class RecurringPaymentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperationStatus {
            get {
                return this.OperationStatusField;
            }
            set {
                if ((this.OperationStatusField.Equals(value) != true)) {
                    this.OperationStatusField = value;
                    this.RaisePropertyChanged("OperationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranCode {
            get {
                return this.TranCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TranCodeField, value) != true)) {
                    this.TranCodeField = value;
                    this.RaisePropertyChanged("TranCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckClient", Namespace="http://schemas.datacontract.org/2004/07/PaygeRefundWcfService")]
    [System.SerializableAttribute()]
    public partial class CheckClient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSPayge.IPaygeService")]
    public interface IPaygeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/GetOrderInformation", ReplyAction="http://tempuri.org/IPaygeService/GetOrderInformationResponse")]
        Zek.WSPayge.OrderInfo GetOrderInformation(string merchant, string orderCode, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/GetOrderInformation", ReplyAction="http://tempuri.org/IPaygeService/GetOrderInformationResponse")]
        System.Threading.Tasks.Task<Zek.WSPayge.OrderInfo> GetOrderInformationAsync(string merchant, string orderCode, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/Refund", ReplyAction="http://tempuri.org/IPaygeService/RefundResponse")]
        Zek.WSPayge.RefundStatus Refund(string merchant, string orderCode, string refundCode, string description, int amount, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/Refund", ReplyAction="http://tempuri.org/IPaygeService/RefundResponse")]
        System.Threading.Tasks.Task<Zek.WSPayge.RefundStatus> RefundAsync(string merchant, string orderCode, string refundCode, string description, int amount, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/GetRefundInformation", ReplyAction="http://tempuri.org/IPaygeService/GetRefundInformationResponse")]
        Zek.WSPayge.RefundInfo GetRefundInformation(string merchant, string orderCode, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/GetRefundInformation", ReplyAction="http://tempuri.org/IPaygeService/GetRefundInformationResponse")]
        System.Threading.Tasks.Task<Zek.WSPayge.RefundInfo> GetRefundInformationAsync(string merchant, string orderCode, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/GetOrderDetails", ReplyAction="http://tempuri.org/IPaygeService/GetOrderDetailsResponse")]
        Zek.WSPayge.OrderDetails GetOrderDetails(string merchant, string orderCode, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/GetOrderDetails", ReplyAction="http://tempuri.org/IPaygeService/GetOrderDetailsResponse")]
        System.Threading.Tasks.Task<Zek.WSPayge.OrderDetails> GetOrderDetailsAsync(string merchant, string orderCode, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/Completion", ReplyAction="http://tempuri.org/IPaygeService/CompletionResponse")]
        Zek.WSPayge.CompletionStatus Completion(string merchant, string orderCode, string commplitionCode, string description, int amount, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/Completion", ReplyAction="http://tempuri.org/IPaygeService/CompletionResponse")]
        System.Threading.Tasks.Task<Zek.WSPayge.CompletionStatus> CompletionAsync(string merchant, string orderCode, string commplitionCode, string description, int amount, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/GetCompletionInfo", ReplyAction="http://tempuri.org/IPaygeService/GetCompletionInfoResponse")]
        Zek.WSPayge.CompletionInfo GetCompletionInfo(string merchant, string CommplitioCode, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/GetCompletionInfo", ReplyAction="http://tempuri.org/IPaygeService/GetCompletionInfoResponse")]
        System.Threading.Tasks.Task<Zek.WSPayge.CompletionInfo> GetCompletionInfoAsync(string merchant, string CommplitioCode, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/GetCreditInformation", ReplyAction="http://tempuri.org/IPaygeService/GetCreditInformationResponse")]
        Zek.WSPayge.CreditInfo GetCreditInformation(string merchant, string CreditCode, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/GetCreditInformation", ReplyAction="http://tempuri.org/IPaygeService/GetCreditInformationResponse")]
        System.Threading.Tasks.Task<Zek.WSPayge.CreditInfo> GetCreditInformationAsync(string merchant, string CreditCode, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/CheckPosPayment", ReplyAction="http://tempuri.org/IPaygeService/CheckPosPaymentResponse")]
        Zek.WSPayge.CheckRecurringPaymentResponse CheckPosPayment(string merchantCodName, int amount, string terminalId, string transactionId, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/CheckPosPayment", ReplyAction="http://tempuri.org/IPaygeService/CheckPosPaymentResponse")]
        System.Threading.Tasks.Task<Zek.WSPayge.CheckRecurringPaymentResponse> CheckPosPaymentAsync(string merchantCodName, int amount, string terminalId, string transactionId, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/RecurringPosPayment", ReplyAction="http://tempuri.org/IPaygeService/RecurringPosPaymentResponse")]
        Zek.WSPayge.RecurringPosPaymentResponse RecurringPosPayment(string merchantCodName, string merchantTranCode, string terminalID, string parentTransactionCode, string description, int amount, int currency, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/RecurringPosPayment", ReplyAction="http://tempuri.org/IPaygeService/RecurringPosPaymentResponse")]
        System.Threading.Tasks.Task<Zek.WSPayge.RecurringPosPaymentResponse> RecurringPosPaymentAsync(string merchantCodName, string merchantTranCode, string terminalID, string parentTransactionCode, string description, int amount, int currency, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/RecurringPayment", ReplyAction="http://tempuri.org/IPaygeService/RecurringPaymentResponse")]
        Zek.WSPayge.RecurringPaymentStatus RecurringPayment(string merchant, string orderCode, string PaymentCode, string description, int amount, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/RecurringPayment", ReplyAction="http://tempuri.org/IPaygeService/RecurringPaymentResponse")]
        System.Threading.Tasks.Task<Zek.WSPayge.RecurringPaymentStatus> RecurringPaymentAsync(string merchant, string orderCode, string PaymentCode, string description, int amount, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/GetRecurringPaymentInformation", ReplyAction="http://tempuri.org/IPaygeService/GetRecurringPaymentInformationResponse")]
        Zek.WSPayge.RecurringPaymentInfo GetRecurringPaymentInformation(string merchant, string PaymentCode, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/GetRecurringPaymentInformation", ReplyAction="http://tempuri.org/IPaygeService/GetRecurringPaymentInformationResponse")]
        System.Threading.Tasks.Task<Zek.WSPayge.RecurringPaymentInfo> GetRecurringPaymentInformationAsync(string merchant, string PaymentCode, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/CheckClient", ReplyAction="http://tempuri.org/IPaygeService/CheckClientResponse")]
        Zek.WSPayge.CheckClient CheckClient(string merchant, string clientID, string personNumber, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/CheckClient", ReplyAction="http://tempuri.org/IPaygeService/CheckClientResponse")]
        System.Threading.Tasks.Task<Zek.WSPayge.CheckClient> CheckClientAsync(string merchant, string clientID, string personNumber, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/BalanceInQuiry", ReplyAction="http://tempuri.org/IPaygeService/BalanceInQuiryResponse")]
        bool BalanceInQuiry(string sourceMid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaygeService/BalanceInQuiry", ReplyAction="http://tempuri.org/IPaygeService/BalanceInQuiryResponse")]
        System.Threading.Tasks.Task<bool> BalanceInQuiryAsync(string sourceMid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaygeServiceChannel : Zek.WSPayge.IPaygeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaygeServiceClient : System.ServiceModel.ClientBase<Zek.WSPayge.IPaygeService>, Zek.WSPayge.IPaygeService {
        
        public PaygeServiceClient() {
        }
        
        public PaygeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaygeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaygeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaygeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Zek.WSPayge.OrderInfo GetOrderInformation(string merchant, string orderCode, string signature) {
            return base.Channel.GetOrderInformation(merchant, orderCode, signature);
        }
        
        public System.Threading.Tasks.Task<Zek.WSPayge.OrderInfo> GetOrderInformationAsync(string merchant, string orderCode, string signature) {
            return base.Channel.GetOrderInformationAsync(merchant, orderCode, signature);
        }
        
        public Zek.WSPayge.RefundStatus Refund(string merchant, string orderCode, string refundCode, string description, int amount, string signature) {
            return base.Channel.Refund(merchant, orderCode, refundCode, description, amount, signature);
        }
        
        public System.Threading.Tasks.Task<Zek.WSPayge.RefundStatus> RefundAsync(string merchant, string orderCode, string refundCode, string description, int amount, string signature) {
            return base.Channel.RefundAsync(merchant, orderCode, refundCode, description, amount, signature);
        }
        
        public Zek.WSPayge.RefundInfo GetRefundInformation(string merchant, string orderCode, string signature) {
            return base.Channel.GetRefundInformation(merchant, orderCode, signature);
        }
        
        public System.Threading.Tasks.Task<Zek.WSPayge.RefundInfo> GetRefundInformationAsync(string merchant, string orderCode, string signature) {
            return base.Channel.GetRefundInformationAsync(merchant, orderCode, signature);
        }
        
        public Zek.WSPayge.OrderDetails GetOrderDetails(string merchant, string orderCode, string signature) {
            return base.Channel.GetOrderDetails(merchant, orderCode, signature);
        }
        
        public System.Threading.Tasks.Task<Zek.WSPayge.OrderDetails> GetOrderDetailsAsync(string merchant, string orderCode, string signature) {
            return base.Channel.GetOrderDetailsAsync(merchant, orderCode, signature);
        }
        
        public Zek.WSPayge.CompletionStatus Completion(string merchant, string orderCode, string commplitionCode, string description, int amount, string signature) {
            return base.Channel.Completion(merchant, orderCode, commplitionCode, description, amount, signature);
        }
        
        public System.Threading.Tasks.Task<Zek.WSPayge.CompletionStatus> CompletionAsync(string merchant, string orderCode, string commplitionCode, string description, int amount, string signature) {
            return base.Channel.CompletionAsync(merchant, orderCode, commplitionCode, description, amount, signature);
        }
        
        public Zek.WSPayge.CompletionInfo GetCompletionInfo(string merchant, string CommplitioCode, string signature) {
            return base.Channel.GetCompletionInfo(merchant, CommplitioCode, signature);
        }
        
        public System.Threading.Tasks.Task<Zek.WSPayge.CompletionInfo> GetCompletionInfoAsync(string merchant, string CommplitioCode, string signature) {
            return base.Channel.GetCompletionInfoAsync(merchant, CommplitioCode, signature);
        }
        
        public Zek.WSPayge.CreditInfo GetCreditInformation(string merchant, string CreditCode, string signature) {
            return base.Channel.GetCreditInformation(merchant, CreditCode, signature);
        }
        
        public System.Threading.Tasks.Task<Zek.WSPayge.CreditInfo> GetCreditInformationAsync(string merchant, string CreditCode, string signature) {
            return base.Channel.GetCreditInformationAsync(merchant, CreditCode, signature);
        }
        
        public Zek.WSPayge.CheckRecurringPaymentResponse CheckPosPayment(string merchantCodName, int amount, string terminalId, string transactionId, string signature) {
            return base.Channel.CheckPosPayment(merchantCodName, amount, terminalId, transactionId, signature);
        }
        
        public System.Threading.Tasks.Task<Zek.WSPayge.CheckRecurringPaymentResponse> CheckPosPaymentAsync(string merchantCodName, int amount, string terminalId, string transactionId, string signature) {
            return base.Channel.CheckPosPaymentAsync(merchantCodName, amount, terminalId, transactionId, signature);
        }
        
        public Zek.WSPayge.RecurringPosPaymentResponse RecurringPosPayment(string merchantCodName, string merchantTranCode, string terminalID, string parentTransactionCode, string description, int amount, int currency, string signature) {
            return base.Channel.RecurringPosPayment(merchantCodName, merchantTranCode, terminalID, parentTransactionCode, description, amount, currency, signature);
        }
        
        public System.Threading.Tasks.Task<Zek.WSPayge.RecurringPosPaymentResponse> RecurringPosPaymentAsync(string merchantCodName, string merchantTranCode, string terminalID, string parentTransactionCode, string description, int amount, int currency, string signature) {
            return base.Channel.RecurringPosPaymentAsync(merchantCodName, merchantTranCode, terminalID, parentTransactionCode, description, amount, currency, signature);
        }
        
        public Zek.WSPayge.RecurringPaymentStatus RecurringPayment(string merchant, string orderCode, string PaymentCode, string description, int amount, string signature) {
            return base.Channel.RecurringPayment(merchant, orderCode, PaymentCode, description, amount, signature);
        }
        
        public System.Threading.Tasks.Task<Zek.WSPayge.RecurringPaymentStatus> RecurringPaymentAsync(string merchant, string orderCode, string PaymentCode, string description, int amount, string signature) {
            return base.Channel.RecurringPaymentAsync(merchant, orderCode, PaymentCode, description, amount, signature);
        }
        
        public Zek.WSPayge.RecurringPaymentInfo GetRecurringPaymentInformation(string merchant, string PaymentCode, string signature) {
            return base.Channel.GetRecurringPaymentInformation(merchant, PaymentCode, signature);
        }
        
        public System.Threading.Tasks.Task<Zek.WSPayge.RecurringPaymentInfo> GetRecurringPaymentInformationAsync(string merchant, string PaymentCode, string signature) {
            return base.Channel.GetRecurringPaymentInformationAsync(merchant, PaymentCode, signature);
        }
        
        public Zek.WSPayge.CheckClient CheckClient(string merchant, string clientID, string personNumber, string signature) {
            return base.Channel.CheckClient(merchant, clientID, personNumber, signature);
        }
        
        public System.Threading.Tasks.Task<Zek.WSPayge.CheckClient> CheckClientAsync(string merchant, string clientID, string personNumber, string signature) {
            return base.Channel.CheckClientAsync(merchant, clientID, personNumber, signature);
        }
        
        public bool BalanceInQuiry(string sourceMid) {
            return base.Channel.BalanceInQuiry(sourceMid);
        }
        
        public System.Threading.Tasks.Task<bool> BalanceInQuiryAsync(string sourceMid) {
            return base.Channel.BalanceInQuiryAsync(sourceMid);
        }
    }
}
