//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zek.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zek.Localization.ContactResources", typeof(ContactResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქალაქი.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქალაქი:.
        /// </summary>
        public static string CityLable {
            get {
                return ResourceManager.GetString("CityLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქვეყანა.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქვეყანა:.
        /// </summary>
        public static string CountryLable {
            get {
                return ResourceManager.GetString("CountryLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ელ. ფოსტა.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ელ. ფოსტა #1.
        /// </summary>
        public static string Email1 {
            get {
                return ResourceManager.GetString("Email1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ელ. ფოსტა #2.
        /// </summary>
        public static string Email2 {
            get {
                return ResourceManager.GetString("Email2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ელ. ფოსტა #3.
        /// </summary>
        public static string Email3 {
            get {
                return ResourceManager.GetString("Email3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მაგ: contact@myhotel.com.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაქსი.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაქსი #1.
        /// </summary>
        public static string Fax1 {
            get {
                return ResourceManager.GetString("Fax1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაქსი #2.
        /// </summary>
        public static string Fax2 {
            get {
                return ResourceManager.GetString("Fax2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაქსი #3.
        /// </summary>
        public static string Fax3 {
            get {
                return ResourceManager.GetString("Fax3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქუჩის №.
        /// </summary>
        public static string HouseNumber {
            get {
                return ResourceManager.GetString("HouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მაგ: 157/2.
        /// </summary>
        public static string HouseNumberPlaceholder {
            get {
                return ResourceManager.GetString("HouseNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მობილური.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მობილური #1.
        /// </summary>
        public static string Mobile1 {
            get {
                return ResourceManager.GetString("Mobile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მობილური #2.
        /// </summary>
        public static string Mobile2 {
            get {
                return ResourceManager.GetString("Mobile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მობილური #3.
        /// </summary>
        public static string Mobile3 {
            get {
                return ResourceManager.GetString("Mobile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მაგ: +99597000333.
        /// </summary>
        public static string MobilePlaceholder {
            get {
                return ResourceManager.GetString("MobilePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტელეფონი #1.
        /// </summary>
        public static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტელეფონი #2.
        /// </summary>
        public static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტელეფონი #3.
        /// </summary>
        public static string Phone3 {
            get {
                return ResourceManager.GetString("Phone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მაგ: +99532313515.
        /// </summary>
        public static string PhonePlaceholder {
            get {
                return ResourceManager.GetString("PhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საფოსტო ინდექსი.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მაგ: 12345.
        /// </summary>
        public static string PostalCodePlaceHolder {
            get {
                return ResourceManager.GetString("PostalCodePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქუჩა.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მაგ: რუსთაველი.
        /// </summary>
        public static string StreetPlaceholder {
            get {
                return ResourceManager.GetString("StreetPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ვებ გვერდი.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მაგ: http://www.myhotel.com.
        /// </summary>
        public static string UrlPlaceHolder {
            get {
                return ResourceManager.GetString("UrlPlaceHolder", resourceCulture);
            }
        }
    }
}
