//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zek.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HRResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HRResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zek.Localization.HRResources", typeof(HRResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საჩივრის ფორმა.
        /// </summary>
        public static string ComplaintForm {
            get {
                return ResourceManager.GetString("ComplaintForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დღეების რაოდენობა.
        /// </summary>
        public static string DayOffDays {
            get {
                return ResourceManager.GetString("DayOffDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მაგ: 0.5, 1, 2.
        /// </summary>
        public static string DayOffDaysPlaceHolder {
            get {
                return ResourceManager.GetString("DayOffDaysPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დეიოფის დაწყების თარიღი.
        /// </summary>
        public static string DayOffFromDate {
            get {
                return ResourceManager.GetString("DayOffFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დეიოფის მოთხოვნის ფორმა.
        /// </summary>
        public static string DayOffRequestForm {
            get {
                return ResourceManager.GetString("DayOffRequestForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დეიოფის დასრულების თარიღი.
        /// </summary>
        public static string DayOffToDate {
            get {
                return ResourceManager.GetString("DayOffToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to უშუალო ხელმძღვანელის სახელი.
        /// </summary>
        public static string HeadFirstName {
            get {
                return ResourceManager.GetString("HeadFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to უშუალო ხელმძღვანელის გვარი.
        /// </summary>
        public static string HeadLastName {
            get {
                return ResourceManager.GetString("HeadLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR დოკუმენტები.
        /// </summary>
        public static string HRDocuments {
            get {
                return ResourceManager.GetString("HRDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დეკრეტული შვებულების მოთხოვნის ფორმა.
        /// </summary>
        public static string MaternityLeaveRequestForm {
            get {
                return ResourceManager.GetString("MaternityLeaveRequestForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ახალი ვაკანსია ვენის სადაზღვევო ჯგუფში.
        /// </summary>
        public static string NewJobs {
            get {
                return ResourceManager.GetString("NewJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ზეგანაკვეთური სამუშაოს მოთხოვნის ფორმა.
        /// </summary>
        public static string OvertimeWorkRequestForm {
            get {
                return ResourceManager.GetString("OvertimeWorkRequestForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შინაგანაწესი.
        /// </summary>
        public static string Routine {
            get {
                return ResourceManager.GetString("Routine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ხელშეკრულების შეწყვეტა.
        /// </summary>
        public static string TerminationOfTheContractForm {
            get {
                return ResourceManager.GetString("TerminationOfTheContractForm", resourceCulture);
            }
        }
    }
}
