//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zek.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PolicyVersion
    {
        public int ID { get; set; }
        public int PolicyID { get; set; }
        public byte VersionTypeID { get; set; }
        public int PolicyHolderID { get; set; }
        public Nullable<int> BeneficiaryID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.DateTime IssueDate { get; set; }
        public decimal Premium { get; set; }
        public Nullable<decimal> PremiumStandard { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public decimal Risk { get; set; }
        public decimal PossibleMaximumLoss { get; set; }
        public Nullable<int> PaymentStandardID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatorID { get; set; }
        public Nullable<int> LastModifierID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public Nullable<int> LoginLogId { get; set; }
        public int PartNum_IsApproved_FromDate { get; set; }
    }
}
