//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSBaseRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.BaseRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfPaymentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfBankCreditPaymentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfNewPolicyPaymentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfNewPolicyRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfPolicyOperationRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfPolicyPenaltyRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfPolicyPenaltyPaymentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfPolicyRequest))]
    public partial class WSBaseRequest : object
    {
        
        private string ApplicationKeyField;
        
        private System.Nullable<System.DateTime> TimestampField;
        
        private string LanguageField;
        
        private System.Collections.Generic.Dictionary<string, string> DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ApplicationKey
        {
            get
            {
                return this.ApplicationKeyField;
            }
            set
            {
                this.ApplicationKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Collections.Generic.Dictionary<string, string> Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfPaymentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfBankCreditPaymentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfNewPolicyPaymentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfNewPolicyRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfPolicyOperationRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfPolicyPenaltyRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfPolicyPenaltyPaymentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.RequestOfPolicyRequest))]
    public partial class BaseRequest : PolicyService.WSBaseRequest
    {
        
        private string RequestIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RequestID
        {
            get
            {
                return this.RequestIDField;
            }
            set
            {
                this.RequestIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestOfPaymentRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    public partial class RequestOfPaymentRequest : PolicyService.BaseRequest
    {
        
        private PolicyService.PaymentRequest ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.PaymentRequest Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestOfBankCreditPaymentRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    public partial class RequestOfBankCreditPaymentRequest : PolicyService.BaseRequest
    {
        
        private PolicyService.BankCreditPaymentRequest ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.BankCreditPaymentRequest Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestOfNewPolicyPaymentRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    public partial class RequestOfNewPolicyPaymentRequest : PolicyService.BaseRequest
    {
        
        private PolicyService.NewPolicyPaymentRequest ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.NewPolicyPaymentRequest Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestOfNewPolicyRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    public partial class RequestOfNewPolicyRequest : PolicyService.BaseRequest
    {
        
        private PolicyService.NewPolicyRequest ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.NewPolicyRequest Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestOfPolicyOperationRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    public partial class RequestOfPolicyOperationRequest : PolicyService.BaseRequest
    {
        
        private PolicyService.PolicyOperationRequest ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.PolicyOperationRequest Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestOfPolicyPenaltyRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    public partial class RequestOfPolicyPenaltyRequest : PolicyService.BaseRequest
    {
        
        private PolicyService.PolicyPenaltyRequest ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.PolicyPenaltyRequest Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestOfPolicyPenaltyPaymentRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    public partial class RequestOfPolicyPenaltyPaymentRequest : PolicyService.BaseRequest
    {
        
        private PolicyService.PolicyPenaltyPaymentRequest ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.PolicyPenaltyPaymentRequest Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestOfPolicyRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    public partial class RequestOfPolicyRequest : PolicyService.BaseRequest
    {
        
        private PolicyService.PolicyRequest ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.PolicyRequest Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.PolicyOperationRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.PaymentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.BankCreditPaymentRequest))]
    public partial class PolicyRequest : object
    {
        
        private string BankCreditContractNumberField;
        
        private string ClientPersonalNumberField;
        
        private string LoanNumberField;
        
        private string PolicyNumberField;
        
        private int ProductIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankCreditContractNumber
        {
            get
            {
                return this.BankCreditContractNumberField;
            }
            set
            {
                this.BankCreditContractNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientPersonalNumber
        {
            get
            {
                return this.ClientPersonalNumberField;
            }
            set
            {
                this.ClientPersonalNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanNumber
        {
            get
            {
                return this.LoanNumberField;
            }
            set
            {
                this.LoanNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this.ProductIDField;
            }
            set
            {
                this.ProductIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.BankCreditPaymentRequest))]
    public partial class PaymentRequest : PolicyService.PolicyRequest
    {
        
        private decimal AmountField;
        
        private string PartnerIDField;
        
        private System.DateTime PaymentDateTimeField;
        
        private string TerminalIDField;
        
        private string TransactionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerID
        {
            get
            {
                return this.PartnerIDField;
            }
            set
            {
                this.PartnerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaymentDateTime
        {
            get
            {
                return this.PaymentDateTimeField;
            }
            set
            {
                this.PaymentDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminalID
        {
            get
            {
                return this.TerminalIDField;
            }
            set
            {
                this.TerminalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                this.TransactionIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyOperationRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    public partial class PolicyOperationRequest : PolicyService.PolicyRequest
    {
        
        private PolicyService.OperationType OperationTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.OperationType OperationType
        {
            get
            {
                return this.OperationTypeField;
            }
            set
            {
                this.OperationTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankCreditPaymentRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    public partial class BankCreditPaymentRequest : PolicyService.PaymentRequest
    {
        
        private bool IsEarlyPaymentField;
        
        private PolicyService.Person PersonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEarlyPayment
        {
            get
            {
                return this.IsEarlyPaymentField;
            }
            set
            {
                this.IsEarlyPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.Person Person
        {
            get
            {
                return this.PersonField;
            }
            set
            {
                this.PersonField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationType", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.Enums")]
    public enum OperationType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MinusPremium = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlusPremium = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlusPremiumDebtCompensation = 13,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS")]
    public partial class Person : object
    {
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        private string FirstNameField;
        
        private string FullNameField;
        
        private bool IsLegalField;
        
        private string LastNameField;
        
        private string PersonalNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLegal
        {
            get
            {
                return this.IsLegalField;
            }
            set
            {
                this.IsLegalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalNumber
        {
            get
            {
                return this.PersonalNumberField;
            }
            set
            {
                this.PersonalNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewPolicyPaymentRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    public partial class NewPolicyPaymentRequest : PolicyService.NewPolicyRequest
    {
        
        private decimal AmountField;
        
        private System.DateTime PaymentDateTimeField;
        
        private string TransactionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaymentDateTime
        {
            get
            {
                return this.PaymentDateTimeField;
            }
            set
            {
                this.PaymentDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                this.TransactionIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewPolicyRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.NewPolicyPaymentRequest))]
    public partial class NewPolicyRequest : object
    {
        
        private string PartnerIDField;
        
        private string PolicyNumberField;
        
        private string PolicyNumberPrefixField;
        
        private string TerminalIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerID
        {
            get
            {
                return this.PartnerIDField;
            }
            set
            {
                this.PartnerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumberPrefix
        {
            get
            {
                return this.PolicyNumberPrefixField;
            }
            set
            {
                this.PolicyNumberPrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminalID
        {
            get
            {
                return this.TerminalIDField;
            }
            set
            {
                this.TerminalIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyPenaltyRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.PolicyPenaltyPaymentRequest))]
    public partial class PolicyPenaltyRequest : object
    {
        
        private string PolicyNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyPenaltyPaymentRequest", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Request")]
    public partial class PolicyPenaltyPaymentRequest : PolicyService.PolicyPenaltyRequest
    {
        
        private decimal AmountField;
        
        private string PartnerIDField;
        
        private System.DateTime PaymentDateTimeField;
        
        private string TerminalIDField;
        
        private string TransactionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerID
        {
            get
            {
                return this.PartnerIDField;
            }
            set
            {
                this.PartnerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaymentDateTime
        {
            get
            {
                return this.PaymentDateTimeField;
            }
            set
            {
                this.PaymentDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminalID
        {
            get
            {
                return this.TerminalIDField;
            }
            set
            {
                this.TerminalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                this.TransactionIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Response")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.ResponseOfArrayOfPolicyResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.ResponseOfPaymentResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.ResponseOfBankCreditPaymentResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.ResponseOfNewPolicyResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.ResponseOfArrayOfOperation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.ResponseOfPolicyPenaltyResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.ResponseOfPolicyResponse))]
    public partial class BaseResponse : object
    {
        
        private string RequestHashField;
        
        private string RequestIDField;
        
        private System.DateTime TimestampField;
        
        private PolicyService.ErrorCodes ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string ExceptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestHash
        {
            get
            {
                return this.RequestHashField;
            }
            set
            {
                this.RequestHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RequestID
        {
            get
            {
                return this.RequestIDField;
            }
            set
            {
                this.RequestIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public PolicyService.ErrorCodes ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Exception
        {
            get
            {
                return this.ExceptionField;
            }
            set
            {
                this.ExceptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfPolicyResponse", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Response")]
    public partial class ResponseOfArrayOfPolicyResponse : PolicyService.BaseResponse
    {
        
        private PolicyService.PolicyResponse[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.PolicyResponse[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfPaymentResponse", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Response")]
    public partial class ResponseOfPaymentResponse : PolicyService.BaseResponse
    {
        
        private PolicyService.PaymentResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.PaymentResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfBankCreditPaymentResponse", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Response")]
    public partial class ResponseOfBankCreditPaymentResponse : PolicyService.BaseResponse
    {
        
        private PolicyService.BankCreditPaymentResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.BankCreditPaymentResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfNewPolicyResponse", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Response")]
    public partial class ResponseOfNewPolicyResponse : PolicyService.BaseResponse
    {
        
        private PolicyService.NewPolicyResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.NewPolicyResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfOperation", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Response")]
    public partial class ResponseOfArrayOfOperation : PolicyService.BaseResponse
    {
        
        private PolicyService.Operation[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.Operation[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfPolicyPenaltyResponse", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Response")]
    public partial class ResponseOfPolicyPenaltyResponse : PolicyService.BaseResponse
    {
        
        private PolicyService.PolicyPenaltyResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.PolicyPenaltyResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfPolicyResponse", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Response")]
    public partial class ResponseOfPolicyResponse : PolicyService.BaseResponse
    {
        
        private PolicyService.PolicyResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PolicyService.PolicyResponse Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorCodes", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model")]
    public enum ErrorCodes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestIDIsRequired = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApplicationKeyIsInvalid = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestValueIsNull = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestValueParametersIsEmpty = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebServiceError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordIsNull = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordIsEmpty = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordIncorrect = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserIDIsRequired = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserIDOrUserNameIsRequired = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNameDecrypt = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserRestrictedDate = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordExpired = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PolicyNotFound = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MerchantIDNotFound = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountIDNotFound = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransactionIDIsRequired = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownTransactionID = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClientPersonalNumberIsInvalid = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AmountRequired = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicatedTransactionID = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PolicyNumberIsRequired = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PeriodIsClosed = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NewPolicyNumberIsInvalid = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NewPolicyNumberIsExists = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationTypeIsRequired = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersonNotFound = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MobileCliamManagerAuthenticationNotInRole = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMSMobileNumberIsEmptyOrNotValidate = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMSMessageIsEmpty = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VehiclePasswordIncorrect = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VehicleNotFound = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MedicalDeclarationNumberIsEmpty = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersonMedicalCommentIsEmpty = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FieldIsRequired = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PolicyWasPaused = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceAndPolicyDates = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceTypeNotCovered = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LimitExceeded = 42,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyResponse", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Response")]
    public partial class PolicyResponse : object
    {
        
        private string AutoTransferProductField;
        
        private string BeneficiaryField;
        
        private string ClientField;
        
        private string CurrencyCodeField;
        
        private string CurrencyNameField;
        
        private decimal CurrentDebtField;
        
        private string CurrentDebtTextField;
        
        private System.DateTime FromDateField;
        
        private string FromDateStringField;
        
        private string PeriodField;
        
        private string PoliceNumberField;
        
        private string PolicyHolderField;
        
        private decimal PremiumField;
        
        private string ProductField;
        
        private decimal RiskField;
        
        private string StatusField;
        
        private int StatusIDField;
        
        private System.DateTime ToDateField;
        
        private string ToDateStringField;
        
        private decimal TotalDebtField;
        
        private string TotalDebtTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoTransferProduct
        {
            get
            {
                return this.AutoTransferProductField;
            }
            set
            {
                this.AutoTransferProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Beneficiary
        {
            get
            {
                return this.BeneficiaryField;
            }
            set
            {
                this.BeneficiaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode
        {
            get
            {
                return this.CurrencyCodeField;
            }
            set
            {
                this.CurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyName
        {
            get
            {
                return this.CurrencyNameField;
            }
            set
            {
                this.CurrencyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurrentDebt
        {
            get
            {
                return this.CurrentDebtField;
            }
            set
            {
                this.CurrentDebtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentDebtText
        {
            get
            {
                return this.CurrentDebtTextField;
            }
            set
            {
                this.CurrentDebtTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FromDate
        {
            get
            {
                return this.FromDateField;
            }
            set
            {
                this.FromDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromDateString
        {
            get
            {
                return this.FromDateStringField;
            }
            set
            {
                this.FromDateStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Period
        {
            get
            {
                return this.PeriodField;
            }
            set
            {
                this.PeriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoliceNumber
        {
            get
            {
                return this.PoliceNumberField;
            }
            set
            {
                this.PoliceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyHolder
        {
            get
            {
                return this.PolicyHolderField;
            }
            set
            {
                this.PolicyHolderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Premium
        {
            get
            {
                return this.PremiumField;
            }
            set
            {
                this.PremiumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Risk
        {
            get
            {
                return this.RiskField;
            }
            set
            {
                this.RiskField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusID
        {
            get
            {
                return this.StatusIDField;
            }
            set
            {
                this.StatusIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ToDate
        {
            get
            {
                return this.ToDateField;
            }
            set
            {
                this.ToDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToDateString
        {
            get
            {
                return this.ToDateStringField;
            }
            set
            {
                this.ToDateStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDebt
        {
            get
            {
                return this.TotalDebtField;
            }
            set
            {
                this.TotalDebtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalDebtText
        {
            get
            {
                return this.TotalDebtTextField;
            }
            set
            {
                this.TotalDebtTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentResponse", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Response")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PolicyService.BankCreditPaymentResponse))]
    public partial class PaymentResponse : object
    {
        
        private decimal AmountField;
        
        private System.DateTime PaymentDateTimeField;
        
        private string TransactionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaymentDateTime
        {
            get
            {
                return this.PaymentDateTimeField;
            }
            set
            {
                this.PaymentDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                this.TransactionIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankCreditPaymentResponse", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Response")]
    public partial class BankCreditPaymentResponse : PolicyService.PaymentResponse
    {
        
        private string EarlyLoanPaymentIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EarlyLoanPaymentID
        {
            get
            {
                return this.EarlyLoanPaymentIDField;
            }
            set
            {
                this.EarlyLoanPaymentIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewPolicyResponse", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Response")]
    public partial class NewPolicyResponse : object
    {
        
        private string PartnerIDField;
        
        private int PolicyNumberField;
        
        private string TerminalIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerID
        {
            get
            {
                return this.PartnerIDField;
            }
            set
            {
                this.PartnerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminalID
        {
            get
            {
                return this.TerminalIDField;
            }
            set
            {
                this.TerminalIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operation", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Response")]
    public partial class Operation : object
    {
        
        private decimal AmountField;
        
        private string CurrencyField;
        
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyPenaltyResponse", Namespace="http://schemas.datacontract.org/2004/07/Insurance.Model.WS.Response")]
    public partial class PolicyPenaltyResponse : object
    {
        
        private string AutoTransferProductField;
        
        private string BeneficiaryField;
        
        private string ClientField;
        
        private string CurrencyCodeField;
        
        private string CurrencyNameField;
        
        private decimal CurrentPenaltyField;
        
        private string CurrentPenaltyTextField;
        
        private System.DateTime FromDateField;
        
        private string FromDateStringField;
        
        private string PeriodField;
        
        private string PolicyHolderField;
        
        private string PolicyNumberField;
        
        private string ProductField;
        
        private string StatusField;
        
        private int StatusIDField;
        
        private System.DateTime ToDateField;
        
        private string ToDateStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoTransferProduct
        {
            get
            {
                return this.AutoTransferProductField;
            }
            set
            {
                this.AutoTransferProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Beneficiary
        {
            get
            {
                return this.BeneficiaryField;
            }
            set
            {
                this.BeneficiaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode
        {
            get
            {
                return this.CurrencyCodeField;
            }
            set
            {
                this.CurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyName
        {
            get
            {
                return this.CurrencyNameField;
            }
            set
            {
                this.CurrencyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurrentPenalty
        {
            get
            {
                return this.CurrentPenaltyField;
            }
            set
            {
                this.CurrentPenaltyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentPenaltyText
        {
            get
            {
                return this.CurrentPenaltyTextField;
            }
            set
            {
                this.CurrentPenaltyTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FromDate
        {
            get
            {
                return this.FromDateField;
            }
            set
            {
                this.FromDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromDateString
        {
            get
            {
                return this.FromDateStringField;
            }
            set
            {
                this.FromDateStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Period
        {
            get
            {
                return this.PeriodField;
            }
            set
            {
                this.PeriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyHolder
        {
            get
            {
                return this.PolicyHolderField;
            }
            set
            {
                this.PolicyHolderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusID
        {
            get
            {
                return this.StatusIDField;
            }
            set
            {
                this.StatusIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ToDate
        {
            get
            {
                return this.ToDateField;
            }
            set
            {
                this.ToDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToDateString
        {
            get
            {
                return this.ToDateStringField;
            }
            set
            {
                this.ToDateStringField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://insurance.com/API/V1", ConfigurationName="PolicyService.IPolicy")]
    public interface IPolicy
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://insurance.com/API/V1/IPolicy/GetPolicy", ReplyAction="http://insurance.com/API/V1/IPolicy/GetPolicyResponse")]
        System.Threading.Tasks.Task<PolicyService.ResponseOfPolicyResponse> GetPolicyAsync(PolicyService.RequestOfPolicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://insurance.com/API/V1/IPolicy/GetPolicies", ReplyAction="http://insurance.com/API/V1/IPolicy/GetPoliciesResponse")]
        System.Threading.Tasks.Task<PolicyService.ResponseOfArrayOfPolicyResponse> GetPoliciesAsync(PolicyService.RequestOfPolicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://insurance.com/API/V1/IPolicy/PayPolicy", ReplyAction="http://insurance.com/API/V1/IPolicy/PayPolicyResponse")]
        System.Threading.Tasks.Task<PolicyService.ResponseOfPaymentResponse> PayPolicyAsync(PolicyService.RequestOfPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://insurance.com/API/V1/IPolicy/GetPayment", ReplyAction="http://insurance.com/API/V1/IPolicy/GetPaymentResponse")]
        System.Threading.Tasks.Task<PolicyService.ResponseOfPaymentResponse> GetPaymentAsync(PolicyService.RequestOfPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://insurance.com/API/V1/IPolicy/PayBankCredit", ReplyAction="http://insurance.com/API/V1/IPolicy/PayBankCreditResponse")]
        System.Threading.Tasks.Task<PolicyService.ResponseOfBankCreditPaymentResponse> PayBankCreditAsync(PolicyService.RequestOfBankCreditPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://insurance.com/API/V1/IPolicy/PayNewPolicy", ReplyAction="http://insurance.com/API/V1/IPolicy/PayNewPolicyResponse")]
        System.Threading.Tasks.Task<PolicyService.ResponseOfPaymentResponse> PayNewPolicyAsync(PolicyService.RequestOfNewPolicyPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://insurance.com/API/V1/IPolicy/NewPolicyValidate", ReplyAction="http://insurance.com/API/V1/IPolicy/NewPolicyValidateResponse")]
        System.Threading.Tasks.Task<PolicyService.ResponseOfNewPolicyResponse> NewPolicyValidateAsync(PolicyService.RequestOfNewPolicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://insurance.com/API/V1/IPolicy/GetPolicyOperations", ReplyAction="http://insurance.com/API/V1/IPolicy/GetPolicyOperationsResponse")]
        System.Threading.Tasks.Task<PolicyService.ResponseOfArrayOfOperation> GetPolicyOperationsAsync(PolicyService.RequestOfPolicyOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://insurance.com/API/V1/IPolicy/GetPolicyPenalty", ReplyAction="http://insurance.com/API/V1/IPolicy/GetPolicyPenaltyResponse")]
        System.Threading.Tasks.Task<PolicyService.ResponseOfPolicyPenaltyResponse> GetPolicyPenaltyAsync(PolicyService.RequestOfPolicyPenaltyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://insurance.com/API/V1/IPolicy/PayPolicyPenalty", ReplyAction="http://insurance.com/API/V1/IPolicy/PayPolicyPenaltyResponse")]
        System.Threading.Tasks.Task<PolicyService.ResponseOfPaymentResponse> PayPolicyPenaltyAsync(PolicyService.RequestOfPolicyPenaltyPaymentRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IPolicyChannel : PolicyService.IPolicy, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class PolicyClient : System.ServiceModel.ClientBase<PolicyService.IPolicy>, PolicyService.IPolicy
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PolicyClient() : 
                base(PolicyClient.GetDefaultBinding(), PolicyClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPolicy.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PolicyClient(EndpointConfiguration endpointConfiguration) : 
                base(PolicyClient.GetBindingForEndpoint(endpointConfiguration), PolicyClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PolicyClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PolicyClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PolicyClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PolicyClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PolicyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PolicyService.ResponseOfPolicyResponse> GetPolicyAsync(PolicyService.RequestOfPolicyRequest request)
        {
            return base.Channel.GetPolicyAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolicyService.ResponseOfArrayOfPolicyResponse> GetPoliciesAsync(PolicyService.RequestOfPolicyRequest request)
        {
            return base.Channel.GetPoliciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolicyService.ResponseOfPaymentResponse> PayPolicyAsync(PolicyService.RequestOfPaymentRequest request)
        {
            return base.Channel.PayPolicyAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolicyService.ResponseOfPaymentResponse> GetPaymentAsync(PolicyService.RequestOfPaymentRequest request)
        {
            return base.Channel.GetPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolicyService.ResponseOfBankCreditPaymentResponse> PayBankCreditAsync(PolicyService.RequestOfBankCreditPaymentRequest request)
        {
            return base.Channel.PayBankCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolicyService.ResponseOfPaymentResponse> PayNewPolicyAsync(PolicyService.RequestOfNewPolicyPaymentRequest request)
        {
            return base.Channel.PayNewPolicyAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolicyService.ResponseOfNewPolicyResponse> NewPolicyValidateAsync(PolicyService.RequestOfNewPolicyRequest request)
        {
            return base.Channel.NewPolicyValidateAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolicyService.ResponseOfArrayOfOperation> GetPolicyOperationsAsync(PolicyService.RequestOfPolicyOperationRequest request)
        {
            return base.Channel.GetPolicyOperationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolicyService.ResponseOfPolicyPenaltyResponse> GetPolicyPenaltyAsync(PolicyService.RequestOfPolicyPenaltyRequest request)
        {
            return base.Channel.GetPolicyPenaltyAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolicyService.ResponseOfPaymentResponse> PayPolicyPenaltyAsync(PolicyService.RequestOfPolicyPenaltyPaymentRequest request)
        {
            return base.Channel.PayPolicyPenaltyAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPolicy))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPolicy))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.240.143:1234/Policy.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PolicyClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPolicy);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PolicyClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPolicy);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPolicy,
        }
    }
}
